apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.: regcred
    kompose.cmd: kompose convert -f docker-compose.yml -o petclinic_chart/templates
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: config-server
  name: config-server
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: config-server
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.: regcred
        kompose.cmd: kompose convert -f docker-compose.yml -o petclinic_chart/templates
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: config-server
    spec:
      containers:
        - image: '{{ .Values.IMAGE_TAG_CONFIG_SERVER }}'
          name: config-server
          ports:
            - containerPort: 8888
          resources: {}
      restartPolicy: Always
status: {}
